// app/organisation/[organisationId]/team/[teamId]/project/[projectId]/decision/[id]/view/page.tsx
'use client'

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { useDecision } from '@/hooks/useDecisions'
import { useStakeholders } from '@/hooks/useStakeholders'

function StakeholderGroup({ title, stakeholders }: { title: string, stakeholders: { id: string, displayName: string, photoURL?: string }[] }) {
  return (
    <div className="flex-1">
      <h3 className="text-lg font-semibold text-slate-700 mb-4">{title}</h3>
      <div className="space-y-3">
        {stakeholders.map((stakeholder) => (
          <div key={`stakeholder-${stakeholder.id}`} className="flex items-center gap-2">
            <Avatar className="h-8 w-8">
              <AvatarImage src={stakeholder.photoURL} alt={stakeholder.displayName} />
              <AvatarFallback>{stakeholder.displayName[0]}</AvatarFallback>
            </Avatar>
            <span className="text-slate-600">{stakeholder.displayName}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

export default function DecisionView() {
  const params = useParams()
  const decisionId = params.id as string
  const projectId = params.projectId as string
  const teamId = params.teamId as string
  const organisationId = params.organisationId as string

  const { decision, loading, error } = useDecision(decisionId)
  const { stakeholders } = useStakeholders()

  if (loading) {
    return <div>Loading...</div>
  }

  if (error) {
    return <div>Error: {error.message}</div>
  }

  if (!decision) {
    return <div>Decision not found</div>
  }

  const deciderStakeholders = stakeholders?.filter(s => 
    decision.stakeholders.find(ds => ds.stakeholder_id === s.id && ds.role === 'decider')
  ) || []
  const advisorStakeholders = stakeholders?.filter(s => 
    decision.stakeholders.find(ds => ds.stakeholder_id === s.id && ds.role === 'advisor')
  ) || []
  const observerStakeholders = stakeholders?.filter(s => 
    decision.stakeholders.find(ds => ds.stakeholder_id === s.id && ds.role === 'observer')
  ) || []

  return (
    <>
      <div className="space-y-8">
        <div className="space-y-4">
          <h1 className="text-2xl font-bold text-slate-900">{decision.title || 'Untitled Decision'}</h1>
          <p className="text-slate-600">{decision.description}</p>
        </div>

        <section className="space-y-2">
          <h2 className="text-xl font-semibold text-slate-800">Decision</h2>
          <p className="text-slate-600">{decision.decision || 'No decision made yet'}</p>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-semibold text-slate-800">Method</h2>
          <p className="text-slate-600">{decision.decisionMethod || 'No method selected'}</p>
        </section>

        {decision.options.length > 0 && (
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-slate-800">Options considered</h2>
            <ol className="list-decimal list-inside space-y-2">
              {decision.options.map((option, index) => (
                <li key={`option-${index}`} className="text-slate-600">{option}</li>
              ))}
            </ol>
          </section>
        )}

        {decision.criteria.length > 0 && (
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-slate-800">Criteria</h2>
            <ol className="list-decimal list-inside space-y-2">
              {decision.criteria.map((criterion, index) => (
                <li key={`criterion-${index}`} className="text-slate-600">{criterion}</li>
              ))}
            </ol>
          </section>
        )}

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-slate-800">Stakeholders</h2>
          <div className="grid md:grid-cols-3 gap-8">
            {deciderStakeholders.length > 0 && (
              <StakeholderGroup 
                title="Deciders" 
                stakeholders={deciderStakeholders} 
              />
            )}
            {advisorStakeholders.length > 0 && (
              <StakeholderGroup 
                title="Advisors" 
                stakeholders={advisorStakeholders} 
              />
            )}
            {observerStakeholders.length > 0 && (
              <StakeholderGroup 
                title="Observers" 
                stakeholders={observerStakeholders} 
              />
            )}
          </div>
        </section>

        {decision.status === 'published' && (
          <div className="bottom-0 right-0 bg-sky-100 p-4 flex items-center justify-between z-50">
            <p className="text-slate-700">This decision has been published and can no longer be edited</p>
            <Button variant="default" className="bg-blue-600 hover:bg-blue-700">
              <Link href={`/organisation/${organisationId}/team/${teamId}/project/${projectId}/decision/${decisionId}/identify`}>
                Un-publish
              </Link>
            </Button>
          </div>
        )}
      </div>
    </>
  )
}

// src/routes/decision/[decisionId]/view/+page.svelte
<script lang="ts">
    import StakeholderAvatar from '$lib/components/StakeholderAvatar.svelte';
	import type { DecisionRepo } from "$lib/decisionRepo";
	import { getContext } from "svelte";
	import { writable } from "svelte/store";
	import type { Stakeholder } from "$lib/types";

	const decisionRepo = getContext<DecisionRepo>('decisionRepo');
    const decisionData = decisionRepo.latestDecisionData;

    let involvedStakeholders = writable([] as Stakeholder[]);
    decisionData.subscribe(async (value) => {
        if (value?.stakeholders && value?.stakeholders.length>0) {
            involvedStakeholders.set(await decisionRepo.fetchDecisionStakeholderData($decisionData?.stakeholders));
        }
    });

    $: deciders = $involvedStakeholders?.filter((s) => s.role === 'decider');
    $: advisors = $involvedStakeholders?.filter((s) => s.role === 'advisor');
    $: observers = $involvedStakeholders?.filter((s) => s.role === 'observer');
    
</script>
{#if $decisionData}
<div class="flex flex-col gap-1">
    <h1 class="font-bold text-2xl">{$decisionData.title}</h1>
    <p>{$decisionData.description}</p>
    <h2 class="font-semibold text-xl">Decision</h2>
    <p>{$decisionData.decision ?? 'undecided'}</p>

    <h2 class="font-semibold text-xl">Method</h2>
    <p class="capitalize">{$decisionData.decisionMethod}</p>

    <h2 class="font-semibold text-xl">Options considered</h2>
    <ol class="list-inside list-decimal">
        {#each $decisionData.options ?? [] as option}
            <li>{option.title}</li>
        {/each}
    </ol>

    <h2 class="font-semibold text-xl">Criteria</h2>
    <ol class="list-inside list-decimal">
        {#each $decisionData.criteria ?? [] as criterion}
            <li>{criterion.title}</li>
        {/each}
    </ol>

    <h2 class="font-semibold text-xl">Stakeholders</h2>
    <table class="table w-full"><tbody>
        <tr>
            <th>Decider{#if (deciders.length > 1)}s{/if}</th>
            <th>Advisor{#if (advisors.length > 1)}s{/if}</th>
            <th>Observer{#if (observers.length > 1)}s{/if}</th>
        </tr>
        <tr>
            <td class="align-top">
                {#each deciders as stakeholder (stakeholder.id)}
                    <StakeholderAvatar {stakeholder} />
                {:else}
                    <span class="loading loading-dots loading-md"></span>
                {/each}
            </td>
            <td class="align-top">
                {#each advisors as stakeholder (stakeholder.id)}
                    <StakeholderAvatar {stakeholder} />
                {:else}
                    <span class="loading loading-dots loading-md"></span>
                {/each}
            </td>
            <td class="align-top">
                {#each observers as stakeholder (stakeholder.id)}
                   <StakeholderAvatar {stakeholder} />
                {:else}
                    <span class="loading loading-dots loading-md"></span>
                {/each}
            </td>
        </tr>
    </tbody></table>
</div>    
{:else}
    <span class="loading loading-dots loading-md"></span>
{/if}
